# Generated by Django 6.0.7 on 2026-08-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL (латиницей)')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в футере')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в футере')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
            },
        ),
    ]
