# Generated by Django 6.0.7 on 2026-08-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название магазина')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='locations.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['name'],
            },
        ),
    ]
