# Generated by Django 6.0.7 on 2026-08-09 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Управляющий (полный доступ)'), ('product_manager', 'Менеджер товаров'), ('order_handler', 'Продавец (приём заказов)'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Уровень доступа')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shops.shop', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_staff_roles', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник магазина',
                'verbose_name_plural': 'Сотрудники магазина',
                'unique_together': {('shop', 'user')},
            },
        ),
    ]
