# Generated by Django 6.0.7 on 2026-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя владельца карты'),
        ),
        migrations.AddField(
            model_name='shop',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер карты для оплаты'),
        ),
    ]
