# Generated by Django 6.0.7 on 2026-08-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='status',
        ),
    ]
